"""empty message

Revision ID: 16aee4bc5822
Revises: 3092e5048d31
Create Date: 2023-01-08 01:08:35.086634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16aee4bc5822'
down_revision = '3092e5048d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenttracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name=op.f('fk_paymenttracker_author_user')),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('fk_paymenttracker_patient_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paymenttracker'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymenttracker')
    # ### end Alembic commands ###
