"""empty message

Revision ID: 3092e5048d31
Revises: 9cfc43d2ddae
Create Date: 2023-01-05 05:32:21.950669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3092e5048d31'
down_revision = '9cfc43d2ddae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_attachment_type', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('conversation_attachment_type')

    # ### end Alembic commands ###
