"""empty message

Revision ID: 50607dc3f0c2
Revises: 80db7cc44006
Create Date: 2023-01-09 05:04:35.718098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50607dc3f0c2'
down_revision = '80db7cc44006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymenttracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('visible_to_patient', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymenttracker', schema=None) as batch_op:
        batch_op.drop_column('visible_to_patient')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
