"""empty message

Revision ID: 523d8bb794f2
Revises: 50607dc3f0c2
Create Date: 2023-01-09 05:07:41.081193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523d8bb794f2'
down_revision = '50607dc3f0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentdescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name=op.f('fk_paymentdescription_author_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paymentdescription'))
    )
    op.create_table('paymentmethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=128), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name=op.f('fk_paymentmethod_author_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paymentmethod'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentmethod')
    op.drop_table('paymentdescription')
    # ### end Alembic commands ###
