"""empty message

Revision ID: 9cfc43d2ddae
Revises: 3130feb4355a
Create Date: 2023-01-05 01:34:22.378699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc43d2ddae'
down_revision = '3130feb4355a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_attachment', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('conversation_attachment')

    # ### end Alembic commands ###
