"""empty message

Revision ID: b7a437b56031
Revises: 29422a3a3544
Create Date: 2023-02-23 02:26:14.176065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a437b56031'
down_revision = '29422a3a3544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=128), nullable=True))
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
